import featureRegistry from '$lib/api/generated/feature-registry.json';

/**
 * Feature ledger — a synchronously-importable copy of the backend
 * `hirocli/domain/features.py`, generated by `npm run gen:features`.
 *
 * It is imported (not fetched) so nav filtering and route guards can read it at
 * module-load time — the preferences tab registry derives module-level constants,
 * so an async fetch would arrive too late.
 */
type FeatureEntry = { label: string; active: boolean; note: string };

const registry = featureRegistry as Record<string, FeatureEntry>;

/** Ids of every gate-able feature in the ledger. */
export type FeatureId = keyof typeof featureRegistry;

/**
 * True when a feature is exposed and usable. Unknown ids default to active
 * (fail-open): only features listed in the ledger can be hidden, mirroring the
 * backend `feature_active`.
 */
export function isFeatureActive(feature: string): boolean {
  return registry[feature]?.active ?? true;
}
